theme: minima
title: Datascience portfolio
author: Olive Lucanish
description: Portfolio from 2025 datascience course showcasing coursework and projects.
              designed to showcase coding skills, data anlysis, and project-based learning.
